app:
dataSource:
postgres:
port: 5432
username: postgres
password: 12345
host: localhost
databaseName: postgres
dbc-url: jdbc:postgresql://${app.dataSource.postgres.host}:${app.dataSource.postgres.port}/${app.dataSource.postgres.databaseName}